# TODO: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place clusters/main/kubernetes/apps/emhass/app/emhass-secrets.secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: emhass-secrets
    namespace: emhass
type: Opaque
stringData:
    secrets_emhass.yaml: ENC[AES256_GCM,data:BsFtTr6Xd4DtYm5s1ovP3IeOD2U/c5iiBXstPNg36QSqyyeNIO1IKWOclbQ1hd8hPcM1f6MQbFxNqzmgNssqvckl+cc3I3Ify9hzc+OO65cXfucmqvQRiz6TPwT0fG2jD0IvjpqURue+jUR89r/EtqofxqL7xbLhI/XNwf0qoPNSZo3NsK1G/eTN8DPW09GU+vsN0GMD0AwVlgvp/biwI/3afEcIQy+5eB5IsI960A792F7P8ZQEOeAzMR4Se/rn5IvO5/+ZuY/eob0zZh2gH9JrtWPtZ+j4q94S2tTrdzY46mUQmE3Rnx3tgzpGPcWTz34dCJSbg76HuVUdzAWB3Mg9ds3ifomWlqI0ca/0SpjbqqjS8lzBjxLhlpLy+4lYKKlAY3ZQczVoh9uFrPY3qgZwrmMTDVSPohWdRPFvHyOUJYFXSCcNP8dUoT7xi8zSV8HKawlGdVO//7BYBIAAW9uv/nPd22SXcyOcyBzZehh+MAkJyH3EHWDCYwd4/9PUOafr8UyM78M1xul7EIZCcLKXsPLfNPVcdxblvnPPtpfFOUkPOC+S7BLTdcu6/T31WwdmDrMpEyJ3UCw8ZuUPoAnl6rkfX085IAP3/HsuLqUw/R/FwYC4FqY=,iv:xcf9YXXi5BzQF83B52UFcNBlc8X/a3dmJFi69QUa4uA=,tag:LWm0/PsOGX6vUkyzwVQFew==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQWpTaWN3WDA5OHgycFpr
            VG02WVVSaFZhV080RldvUWFuTmpvYXdMK2c0CnZhK1I2emRRM3kxQ0xZekF5aEI1
            RFlPR1NoMjBwQ2JvYjg0Q3B5ZEZ2VEEKLS0tIHNEVXhDcVp4bnpJWUpoWm16QW0v
            Z2ducnA5L2hDNEs5Sk1aY0NIK04rOUUKQ+uTHHFgkWXB+StWgz+3dGd0Fi6HyPM9
            htfmcRIyc+vciGqIXCfNMx6ZE9H3b9Vg+A3iEGlqi9xDz8PdEfjK7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T07:43:08Z"
    mac: ENC[AES256_GCM,data:yBjVocTBcKQKoy957rVvtN0M3nPUksQK5QB3myC/hWPdNqGQhbo9RryfuEd5oThZwqMMJMeYYmMGVsKBjky+/R/gyy2x4oAzzLXV+OUI89lXhSz8b52W32P4lpPhL/jlj4jE2qekEnxJMIkHT5tR1ReMlA+6MQW3o0LVlPijzq0=,iv:ayacyMxTSxGMaKqNdlRpRl5VqclOjbtHyWfWF7BB5aA=,tag:bam1tW+EHmFCaRsXAX+UsA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
