# TODO: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place clusters/main/kubernetes/apps/emhass/app/emhass-secrets.secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: emhass-secrets
    namespace: emhass
type: Opaque
stringData:
    secrets_emhass.yaml: ENC[AES256_GCM,data:kD4OEdSI/A+VmortYjbDcSh9j4MGb1tFy3mj8YyXNBah29vouWByxEv6dAIPBqoWDzGZJSoUFo6R2CGRcj8Ffzrbx3swsV9EhJfoKR6gLOL2mFuxRUIpGKJu6cH3DNdtIRVxkOGgXJ9mWezftQISyYoJSH/ygTRXnE964zlXnvEO4H1BxiAnMW8iBplsNbvxdxdq6xiMonGJEvVvQpkhekaJlMss6vuFo3RDc4dLMi92YQ5SxGq++g7xOLxbF7BBhr6shLilumFudt5NwvGrPwLt/ZdoDeKuW8J/NfLb9wMtQJUYdJWyWLm3PnA4ajZAmGMP5zH0ng8CS8+PvTj4ZLLS3mmm7KtlidlsSjb2zoAOORbgGRVWgK/sWu9OkAN635xnpi7KxluxE14LJuhz5l4kTaulKMuNpxb3/tUniHA6jDcjCoVhxwQ4fVUPOLNPhYrDU9t+WHH/gQ2DFqSZe4sXAkH9ocg67ACs1ai4y3f3B0+TygEuYXv4eVckYKzw2M8sDTPPoJodqNDaiW2R1hrXOAhTlO71nOfIa5YMTXHtOzTa/c0eOpeVjwW5HCgoMbzVrKkpii/1EiaJ6AmwariYWMYFOOgsIrk=,iv:/yF4K1dkbrmwmm0rxj8fuGJNe9wa9Z51DpvBHmgYx4Q=,tag:s5I9VcG3ITj7cIBvMBuhPw==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQWpTaWN3WDA5OHgycFpr
            VG02WVVSaFZhV080RldvUWFuTmpvYXdMK2c0CnZhK1I2emRRM3kxQ0xZekF5aEI1
            RFlPR1NoMjBwQ2JvYjg0Q3B5ZEZ2VEEKLS0tIHNEVXhDcVp4bnpJWUpoWm16QW0v
            Z2ducnA5L2hDNEs5Sk1aY0NIK04rOUUKQ+uTHHFgkWXB+StWgz+3dGd0Fi6HyPM9
            htfmcRIyc+vciGqIXCfNMx6ZE9H3b9Vg+A3iEGlqi9xDz8PdEfjK7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T20:35:15Z"
    mac: ENC[AES256_GCM,data:T6RuRu6pvjq8B9yQRNGOjFu8l9i+IH/v5W8jVNqqT1YZppD8O+v5Z+Hu4K9KcHArjy0klk1QeQGqfVCh7hA54Xzu/lHXzBjE+AxSceWSppU3dpfID4rbS/Yrns/j69ukhDnotdfcuP8IG//tn8F+EEiOvCOldm3DLsSx+e+u/jA=,iv:uNoms3SathqLXqRi1wRzeuBUzoZYn983dVlbHWPcgD0=,tag:N0PBQEshbXxPuKbXRJgn9w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
