apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-runners-cleaner
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: home-runners-cleaner
  namespace: arc-runners
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: home-runners-cleaner
  namespace: arc-runners
subjects:
  - kind: ServiceAccount
    name: home-runners-cleaner
    namespace: arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: home-runners-cleaner
