apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflareddns/ks.yaml
  - ipmi-external-service/ks.yaml
  - kubernetes-dashboard/ks.yaml
  - librespeed/ks.yaml
  - router-external-service/ks.yaml
  - makemkv/ks.yaml
  - tailscale/ks.yaml
  - influxdb/ks.yaml
  - jellyfin/ks.yaml
  - plex/ks.yaml
  - syncthing/ks.yaml
  - ceevee-webserver/ks.yaml
  - switch-external-service/ks.yaml
  - truenas-external-service/ks.yaml
  - timetagger/ks.yaml
  - automatic-ripping-machine/ks.yaml
  - actions-runner-controller/ks.yaml
  - actions-runners/ks.yaml
  - immich/ks.yaml
  - paperless-ngx/ks.yaml
  - home-assistant/ks.yaml
