apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kAKbRSChIlbRwPu216xl4QXPmtBBBVOorWF4Y9H0TK8n9MUg7rI3Owt2b//XLfysDAYiTe83+H8XUvz05nlcTNZ5SHeJ+Bo1R1jdWhmRiFIPFXDV7QrG3rcSxtLZ6MX48rABaCIgZgUYDCNRHFVuwG6WxgQfaUZtS/Jb7M0hz0G2+Ywq51Hf2uIoZ2m8zO62Yu+Dw0folDCxsODWvesvFBZCroWAEQhEsAd/7CQGWXzTu0tQ8z3KZXqAD5rRgAraWkZEAGAhg3cE/p9d1ikRXb6jfACX1qsnorFWJLyJ6+EO/r4CvCXmrNSpvRFiNVE/D+YsjdAgYHgVAyas30sEc99jbq/tQ38y9wJ2Mm+bfAlwFvc9jSOe6jnfSsMZOVOP,iv:jvOSpFUynhEvBbt+WObmVM3bJRfGDxKSkPp7MynkrTU=,tag:Qn9nsonrBeV1A64hU/Vzxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:C7va6XANTl99rDYBm9Uaf1N8Pmd1X+pK+T0fU77Pa/VqKgv6wIsrqkqoFNp8Gve0r9ZyAVs9Y8/7SG5euVBJyDZQBzPg/MQBRfA3tTW0JehZ01Xt/QbCRBXdymrEAlvAOtQxybhjQI8A49y6u8xJUk54qeRLOX/0QuRyNnOit9GfQX2krxb6mCxkB+zweHt3uDQVIKXgyZYdE40AOMNUTP5EsXJnp3X+bzUvgeXAuTVtGhpaM3aXvRSiyRUEIA7DhQfSY9N+9zeBJUG4HA==,iv:3ewYciLy0/eKwxxGwijUeFpG7dc8EDLZDB+/5K9w+yo=,tag:9VCtVFMsKQl8mlzD/neVfA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZSOtusCK4bjMoAqzdZ5Kmqr1C8TyZmZYjpr75TPZbfaq2lZDnJXqANiqWBokBrTn2MLPTxlu3wmxgPgc4ovdO0sq1VN9i8ruUbHIeEZPls/AMJpIC/gXfs+DqvKaI3lRdBw3YxEA3Bh5IGbKUzvDhydFJlvZtm7P8uPY/bl+N1Qvwt+A4iDeuQa+QySMvbwug9o7LLtRjg0XU9N/EVkgrMf8lpoIWcanchMk,iv:LeXsk4lXy2Lb5H49BtblnDsyk/eNufqD1DU227I50UM=,tag:f4JWV6KaeCO7f4e07VrsOA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RzRnOTRYMCtZSlp2QVNr
            RXI4c2swb05obkVlTGhFT0ZqMzJiMnpGd0RBCjlsTExSWGd2eGxEYWJmNFk2MFlj
            K3FETHh6L25PWHFjUG9KK3U3STE3Y1UKLS0tIGJCZlBCSVpVNUZEQnR2S2pOKzM3
            Ulh6eVVaZnNuVVpWOUxZN3ZneVlyS3cKnjbNN2nZGslDXXnqcIgWjPNLk3KUwnTe
            wT/LbiNSBWjLL/y3dOnnid9oy1LsJANwci+6hc7CI18Hd4EdbXg/yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T01:08:51Z"
    mac: ENC[AES256_GCM,data:ynsjkGQNPjV1Tuxrt1/dPhR8entyYdzbmpHGY/1dnoAxwytfQ/9RcpmMi5wKbmNiOUGXGHrfTkszv9WA22/K3/PBo+DyTZ5JZP/i6U61TfN0dd2v0quulW0Nv/3FgDga4mZyeGhtZTqlJBr37DMOGQ5GjrLqGQx7uo3ViWom00U=,iv:6Uz9xbFzQXm/2plMigvJjG49gk48w8r/d7N1xG8Bo5M=,tag:kRypR/wDNNm99PVNaNS6eQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
