apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TNsH3ZQfkka4J2UuFdNxrU7Y6WgwNWOUM9AJdLSLbQb2o1/xqVzO75FbQiw5Uz0MbXXRYkFsolZovldm3OEFziH8EHjc0yNgCMNpgncFtV8pr/GDNU4Ib0hivaPHC4QK4XHh2NUYd3lJ+20HvqxRjVsMBpkbqMeo0s+arpUcGrhHaM8QSIUGxwSrcsb9SKnDVKlekxAY3wejPmQ1K+UQr06M9Y/GfNLs1Skqbze6m6j0TBtI4ZRQ24v/0CtTBji5SKgJqEGOND1Hka+8KUeKDIiwaAUp4U2m714Xbkg/5+zlUqEPQVxA6QqePvLzJWVnvM4+nzJFcl+fmawlQj+Hq0EhAs6ZfZYdD7sHmDlK8pCofPEPwNf9DUD2RXPQJnu6,iv:DLsdiiuiDxiE13LOb68IaPi4mvVufOSLbpSbczugPHE=,tag:CzDFGpTXtDG7gIarhS0zvA==,type:str]
    identity.pub: ENC[AES256_GCM,data:/ejxJBh5XBSw2hbirEUpM6mJ6ZnehfdWzZDHxMOM1Kl8x1tz702d9HjBXle4FgMSBN9cZsZ7VKXLgPsdPHcw1lYz5F2mDPQRuPuGAC+N6JrTirRoqpLnsLmqNpLabcB2fGh1IBRuaF9/2HjWnQeT9MehENiVqZ2YQ4oa0hnbASweCJBJyESEd6BkcRBVGSKEac77EBuUzfAkdkJSI2y/NRuogp0HyA9xknP97sgLPnXUr/9HHo1LGNC3x82cHA+PR8v7YWPTy4/2jhh5nA==,iv:MPl76eJqdWS0gBZRr/qsQc8T+YUo5ET6FTZJpZdCj0o=,tag:+mJpQ4s0rrve6LbZAmuDdw==,type:str]
    known_hosts: ENC[AES256_GCM,data:NsOGBIYvgBDgING5TiloOIMX28aEKQY/LF76MdBJaAqZkRXscVp2c7XTrAWAsZi/w15B3jTEGVDUWRmyN7F6DXInrVUojDJaQvfBOOzYd8nY+5E+97TIKJ0lBUrnDdf2gLnAJsKYL5Um1sKF2mmJOMRu4AbhgVr6QBUDcERp7RP+guG5c+zLM5l5STuCOJw7AZz4lcGEZeIpeZ27VUocTavIe4vhEJTBa5sU,iv:1d4Da3cwItflco4JGUZM8X+ituElc9Gp9d6IoEJ6ZXo=,tag:ZF88iWTUrkR16V2fOvXdcQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS1FZaDJJU0ZZei8wZmN3
            VVRLa1ZIbnZ4aDJmWVg0aW1mSmRneUlONVdNCnpHU083cnU0K1FqZ25FdHNvanJq
            SGdObDhOYmVuc21jZGdVclpFSnp4MDgKLS0tIGoxUHFCdWF3MkdJYmtFUDNPc0Vk
            YS9pWXY5Yjk0cEVrd0UyblNBVTJtQkUKygaaLfpL1nKhpx7+ldnIfXRFh5pQmD2Z
            zuJ3uBojWDE5TrYtcThhtSfp0BnJRmiTnYSlv1KXacNzysAd1oEI4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:56:56Z"
    mac: ENC[AES256_GCM,data:JS0JkWHB/sY4CeUSNGDfBko9yZO2ciovNC8ub+u5tI9wQsuLYQepoutRdMAG7IpnTo7yUTvxnYmStdo/ANZuPE3uZWTg18Hs1PJr5JL+KqU/yKFd2llTnSZXUuk+fUd7eXFWJxNEXxaoh8u2IVBjn6QbzHMBzjtnlISO8k/3i+c=,iv:CtHERre2q+6LRgPmX7wakh4c6BwlLsleBHDSJH2bmLg=,tag:CFbiNNeduZCzDW153ojIMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
