apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LLw3meYruwSine3feXHs0nEJkgqsa894Eb5mjkoyHoix0rx2QkJQ6y7bSIGxYDO3OjtuKc0Awo1GDEcKMySS9jjjO0FOkoDP5PVLhZjRNLApKIeiWiYWmr0R1AVqd2scSfKrk7ZpeKz5+XQw1GY2ALiJwFqJsSod3LU+331C2HyJKK8uQF2JHUPE0U7j/2FWhLie/ZO5vDxjUmuQfEJdZjrhTXkmfNKyn3COawIxMnQ39ROI32W0qWWelsbmEHosDNwd7jtVzvI1O3hKzYkmpynNltcGRMSLz4Cwp7ZHyb58LFmJA5Mzz5MCa8TT4yfn9sOxPA4iqIyDVqu2F5++nKK1lMWvZ3d5rDi6UYYK6VQsUUUcgGBBoq3f+jFMIzgJ,iv:T5dGcJL3ToT+CdVYNy9Qo7gnvUOQICD/zQjNL4tM54U=,tag:0XPiOjB5DduHP5atQL9GMQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:92GoRffVjkZw4+iC9ekeUc3+tyTrStTjfCzylSHsJfz4Ps2IHSgCl1Y8eataHAYTPlJags0sUCPbdXylr07S8K95QRvC5dvqWCf53Pt91VMELji3A2xGU4aAjMAb3B/baJA0TluV5fS5KHNzGmMp1urcdVYS5gvz3bB9J2k97PbEwxs4cauXgYbCLcrTvpDf3qte4Wj1Ox4HJkOTmyqcIqF1FYo8FWL4j7pxinzpe16YSvdSdEuPOaEIQNwCXIMWqKuJfGoChGcC0P3Qjg==,iv:1bxOBnz9IZFr8w6nSlF7frc41xfYnkdSvE5t+5PnOpk=,tag:Lm5tk0ArYsFbgzsA3eElhw==,type:str]
    known_hosts: ENC[AES256_GCM,data:VN9UTcVGY0qY+8Y3HI22K7mft4FS2OieIziqh4aKPl4KhwREal1IZ/oD1mmTHslUsgXbcAEVzkLXjqEWHW48n7wnTJF1sweLchCYgnZ/HxKo/0jMdoyplxdAztb+xlpNAhU3PTakCt01VUKLPHBwttUcHpGuJYw594A/c0U+vsVdoNaGXObXS1tL42+eNfFqqjepT0wOtj4rxqWpoL+9s3ksXhF73UPUVeLe,iv:1LhVK70uGLVe7a3ZcRvjh/un1g0VocU/GROrroFWT6A=,tag:Zfgl03S5MOpoSlgBFAE4zQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraTZpTlpuWlE5bHhHbFdF
            REJ1OWZobTlXM25FRnJVMlRkeURTL3ljclMwCkJkcnRUWmdBRlZlQms5c050UTZZ
            aElPcTV0ZmpzMFN5aUlRdmNuM3dTTTAKLS0tIFdJbVF5Z3RnTCtJWWZKZ1htN2d3
            VFErTUhLYm9uTTNXU2ZtUHdQdVh5TEkKbxyEUZIpgLxfz/1aZyKejyz+9PjISBlx
            Wl2tyV/laTOiJS4Q5G5EbsA9OYMmPEdAq2PutY/BVMP4xWktOAdhTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T00:16:06Z"
    mac: ENC[AES256_GCM,data:JfivBXms1vq8hccJy+A4U0FLB68JLOFRNWF5EnMlRT65OQlhkwXT/+zyAvyhelnGat4bz/J4lUrKkcJQ5AQGwA+6Ew7MUTOXKsEQHaqW8zWuaFvqkqwNQza1wMx0ZO1gtEYUg9BW8aOIRqTgjkVBCrpwsWbk5aO3G5bYgn1o690=,iv:RQG0hEyMiXOZ8iV6TC4RpFCX5C0Iuzp0ZMQDXVA0q2s=,tag:D0zbn1AkFZXQA39VxS14Sg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
