apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YeKkOoqFdU14vf2BxjPF9REzJsLY+hSCh108k49lZ+n3lzyzwQRX3G8tG46Lg8ubON04mQ5XVzlea9ljcWwyoB7tovn15gKWPIBgsHWgFfFDTHZgU7evvpIwlUnw63zyguIRaxbET9p4epWpTNVcWgkvMnHX/Or8iU7do/oK4XEfc151cVQRmNCz3LaFNRXm94dfuA7MIV8e5z1yLPiIm1OjN06yCmGXQ3ms+hfuLYXWRaNZRMkXDQZvliHgT6PPwul2vcGo+qbY9N8Tq9JibRNOeDEPsKlf88fnSpWUGwBYRyzT1oAFeVdONyYKjPM4NHbY9ytHsc7z2SrF/VZZM/s6xu3mZ8TLr0KLThMl4x12TpYiQ0dV8s93WNUVPNR9,iv:/PHs3lHhuGg7ZTBbz4GaOmVdG7DyR5BSz72jmmYJ7BA=,tag:tD86Zm5sCr98kbyEfahuIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:9z4DD3jzTgbApHNKks6CpTSGwv0ZkO890ygSROQ/VSIArLvzYw9+OgTfEZBtwiV7TcpHjDZsqJgrFHk46CA3Hofad7Z5LQ7lYFmZF+yY/xALDAOxl5UEKWjX/vzvamh7B/0Q95lAVfdQ1dH7QWK0HUljpKUkGKu3cF/uzj871CwZJeJDhRYdrjpXV2CoIlPAXPLNlfroWS6hL8q0UoFf1a1CYE4Kscr8zn62bMo7D7jqJU43mM32Uln1BC8uxgUNRSstSDIp/Br9oy7zGg==,iv:kvCeAJynSy/ajdX3HQtGY/Msl7mQ5xIz+tCxw8g5AEU=,tag:hBlvo/PHyJquMe/qpn9l7Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:cUBJibz2k1jugbY50djC+dexC1RRsmWwNITgiKeZSEE2gKwZ0W3p5w2Yo32NqCCE9tAQH258IfkVO72CFWEDHIwikRfoY1GBqeN6tdZx9rJ5CQcNR7Z5jgRSLdcpe+D4cBajWsoBFqn+r4De3sQmE9yE/pUm09ASBQRQgDuraYPhz89h9GCeZmBndiIliRMHDBVyhkNj1A1F1p5UfjYUyjkut8DNBr7Ea0Kg,iv:Q73yJvHkAysZiFRSNcm1k+ngbhJISzn5NYaisobOpIk=,tag:HKh/KxY7y4+PieEVKaqgjA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTlhuUTdoeWlJV0x5cDJo
            Z0tIY1RiNENlRVJhMlh3OVFncDVKeCtSdURvCm82bUErOXgzZmFFN09qemN5Q1I0
            MUh5TU4xelFNNDZQcXpiSklzQy9nU3MKLS0tIDRwRWFuWitPNkxQR2tRZXZBK2sv
            UmVab0ljY3BKNC9rQjVZODErdjcxUWcK+W2XmYoq9ycbA7Lc2qK1GdZzkCiROoKp
            EfKtqSVpUgVYG5XUf4rhS4tpe0d3Mdy3b/HO2jsgggZ4iibyzNhaNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T00:13:38Z"
    mac: ENC[AES256_GCM,data:rqA/TZUJKv04tyalBjJ4QcXsFNqUSnqCv89ekB4yAtAG5/AIFCdKI8s4OrO3uV/qyVNQDVCSvZiYTe0EzXLNOGd+5yFmvVe46TojKWMc/kFJRFwX7U2HOXOCDpLK0Bzh5bHWXtEPORnI47y5vezm7/kZKZGLJuzK2tNK/kOnwZk=,iv:QWow17F579CSuLU9MqCfx5NW3AY5KQx+5xg1EmTu07Q=,tag:0qz6lqWfqGvEgrk9TBWn3g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
