apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zegjBE2HPC+2K4e0L81TvGdV4sPK2m6KUGkFjn07OQRsC5qmQBFy1AxqEhssesafeHx7V7hOItNTsbjxLJ9isgTBhtyXCY1Ukh6DR7QLXqDecn9lqlN+SoRjhAmwLWiAqr7K539a3wcvAKS9K+rPiAzN+Oy3OaAztZBK5nABC4iZnsjPOXZcELr3PYwMmDtnQ7eL9E4oPYAO962Bblg3ZsJvXdmLRRySHNiFuD7VIpA0Ay21DmpOl0/R25RddxKdKF3vqdyNr6KsP2aEWaIWHc32sPSi0Edf61UaxsAUYhz+F3Mn0YhANeZ8V2PXTtJYID2cUQXxsMw3aikpwUyzd0ptZcHQ0ixRYoJC/2rPo4ig8NB5wgv3kZnyODONw1Ot,iv:pckWcNJG9DfknAJfdL4SlIhXpBUGqKTycnwATbUdkr8=,tag:MXKwfuP+9EvSqxrOUq8sMQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:UC4meKsewImf2BYp/sQbtUXDubl5GYJydXR7rgGSoYVnmsNgJDCht11mnWoes/TjkDg2TFdiri0S0F/VBrrRyoLs5P5PVDxyzxEXtUMI4/m8TQrBQ2wUPNRodZhG7Kh0HysA+XCcBnY9VBbx2YmM6Vy+qW8Q4uuJBLDNWFPfMniGjdhl8hUp07vDCfaQHTkQHM9HrA9DJRP/PeXqxhKdKbZqMC/l5m5Er/18b0va3TKCc+HKW/NcwSKDdLZHfl3tepJWHjCWKeGKVbU7iA==,iv:IuqOT8fgA7kvuCeWXmEg551bR+NtBB2qHC5FW+JTGfc=,tag:8W3FdAViFcidl8k/IRnZLA==,type:str]
    known_hosts: ENC[AES256_GCM,data:x36VYcFyN4k1OjSlcbXiJ2JYvbQZtW8FTvFvZqncsiM+EkcPsqPiB/sT1G8g3f2xNob6t08QtaoMx8hGL93imHDznGerlQ/a90ef0PKf/VM1zVNg+539Y4xEqlGINE+zMO9JP1+IAo7FCZz3ZfO7/rfax2KCRRTFWvteOIieqiI54+BewLMrY+X4O7qb0R4007/IFdtmfO3+HQbGv4A2l8SjuTI5rlYRh4jN,iv:ojmeNiFw1FlMZVOE57k9p45MHMbY0PJ+6jx7fjnJyDg=,tag:GAvo9udIQebkCcVXYgyggA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUWd4K2pHNm5zU0ozQW1U
            QmFKTUprc2VJQms4Q0pUcTVxa1hRZFZxRXkwCnR0QkRtV1V3QWNvbHFJZkpTNitl
            QUlRellkeHRNYWpHMUJxakg5NzU3MmcKLS0tIGNmT0ZERnNEUWpMZTJEdWM1ZHNu
            MmZiNHU0bVh6TFJUaWJaaU9PV0JYS00Kd/yk27u2qmC7r6kGPP16rCFHAS0iegvM
            dOqmEY8Qi951uYoOwjC9+bEQHM/bg4e3c5Xrkp6GtgIADj86Y8eYvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T20:32:09Z"
    mac: ENC[AES256_GCM,data:phpWue2W1NpXnAXa9klso1YJOohWp5U7UGosCbjJBEDkDa/8mUGoYyCSy2z1euzpIBC0DkyP/r9R/28uLIjXYb3ew4xicWno0vD5HEiI67tbtR276C8aTvqMAOU7D6hX0BOyTgE3jM8rIYQZmqOAuQOyn+pcFvm6W89OcoixCEM=,iv:KvBFjluIWo1tz/dGXDS+2+OJpxJBEcKuJODfuBi6YNU=,tag:KCtA2hhi0QQ7hsMYx5465A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
