apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/Vk+GbZDagt71NsrEDjTjVg1W03H9T3oQJWvxWZolAe9xOH1IR8g+oknOKMR2NBsP7fr3io6I6b/c2RpdWPgztJ2gdgkUoWB4KELqeHvuzHYYZe/Y1etilu/8vvhMweK8TeP3D6Zkfecva0ddFWiv7hFSo8lJvsgT85cHmCqwLsXMjuHHveJfdwcwjftTJREn6uqU8n8LVO7pX1wL8knOIxAvBDLLQJxqwgSKITSpsOXGr0oEQkfdVkvu/cgEIiW80iyd7J7r010Hh7oRhjJrNYzWGuxjs2yJ8riowydkD1GOS9gqxnOm/1y6bNJ6o72NEHqRO5zDDwZEmNPmoJmGl5ZaC0JnjQcy1yWMonuT9nC4z6qNOPATJnrzZAgyazg,iv:K2AzzlS9UUFDQv8eSk1mZstAPyLZHUZmmoohWIxeWjc=,tag:sE0WDoEV3B6R2hDo+75Fpg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZnjQ8M5SZl7ZkwzdS8ytP1TDRr1ee3J2Y/OBP0A/IAMq2autpIv9pUpn2rDVyyRL11CR/g5+ju6dafg0twUXtyd4dUE1iAx795a8KolB/HN8hnD7OdlvaUPXO8EJA6LaWT3zOInt2lbuuxhBU2jY8nKQpQ7aGqWDKn4mGFwSdM9zhR9Ij5CcX3X1GO8cyN4+WVbvdZS9nLBAuJ42cDgJyXMmqpti2h0r58b8Iyls/xTbTY3fB+6I0sv+e97e/niRkSTvle0GHe1dB6QkcQ==,iv:pXOef5YX6xpk2xFNOoaBVelTojqy9yk91bg/hG0X4R0=,tag:9s1CTT41aFbDqpaOvJIrdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:klSSYUmNM3ZPJO1bF6817QYfBjeBh/Z7lhj9eSzIx9Nz+uxDOOiCQTLJ//vGfdbGyr/klgXesVDPjHfCFFl6IZvZEK01uHaw1keIxgJXCgxfCrTp5YYALlxE7IgGQXmlHLey2EwjSvJ+oQblxy5rGsmWaWfnqEf5H/B2AGkRHLlUn1XK9fXD6wpUP4lNIkWEDJdQ0cnM0Y6Y7+T7WYWGd4/SVFKsKcErUK17,iv:rgUgd8qwcu4t5vic8Uscilh1w5ZNQtXHoJORl+2X+lU=,tag://tJAabTZnQk4IdwUrt8TQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUXkwbElyeE1MVHhmSVIz
            WFVCNEY1aUlOblVSUTI0RWFDbHVZWmRWUWhVCkdQVGtGS1dwS3NUNld1ai9KSW5x
            d0VtLzNlMEkxTFZxcXNGZitWdWxzODgKLS0tIGVXZmE5QjdkcWtHSDRXM052eVdX
            NkhQNEtHb1MwUm9WQjIwVU5pYzkxODgKOfepBZIu8sruDFcK/hlF72/2A4vKSvdE
            fRtL7ieTu/naXGx6V29oYS0IaYKgI5gVwYfM8wFUrDwAGbN+80AKCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T13:52:41Z"
    mac: ENC[AES256_GCM,data:Qk44opuIMP6OrhwWfx1Haf2CPefBfgeyGsCLRnCwL1zXgKgTu+W+vfwj0Zo0nOoBqSXt8ulYMVFZE//YNgGlNsmkpsF6oj7OVKGrcA7lrshbUxf+JK6ZEWq2HG1RA5iOQdaD2yMsFPikK4u02nNSpJ2rYV7LtD6a8Q3lWc5BeN0=,iv:4+6qlomT2UMMDOaoinHWhbMhK+oDul3rBJGcfLmTLP4=,tag:MtPqWYuzfGIwhuTllIUiuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
