apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BMbCBTHUpKYUysWPIuU0JQFH5Rs7qklG50nBL1SjgtpyF3HkWEs9IpkR2x35BEMy+/HiITbdgCELDrtjqqVSKrW2R4obpi09dJx+ndHAdexoRmmnsqdwDAyNLVbiTPhogQrs/8ECGP0GXTLE7ENboao2uAuhm7F6c06GhfcfyQMBK+3spoXd72x6eSPlfSL+KqwhN4LCe2T0UotwCawka1UzLllK9KamQQ6kKxiqdVom6OJXSqSMlxU5dHrE0a4eqQKEzGaqznwtUu68bxxtPM0BT9nlYwnnGD5qltPGP1rZSiZJlqw88CnhNprs94c5LTZIquDXihLnTc2hfhK+Ol2ok6e0E8TaJhoAlwW0qIVtBbFLyXeqekZ0LZyAE0dq,iv:KeuNiyXfKWppufE/Yv6DAIL4J+Y9K3N4tDMJXjL7Ojo=,tag:yz4Ag2OpROZVH9pHsZO1tQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:dp+gN/elacTe1hFxlpoAJHNhZ2nL41DmN91Ursx0Xe2qDkKYUKmY9GICcLlwsPNhcHAZv/H216O4LXuye10uQZ/2O/MMK67mIiVBCfUdwh3uumpRwDfc6O6cdorjbnbR63oCv8UQIlAAxI8gs8FBeKvdUgzCHcz9hi8clD43f0nTe7iOK7YmgY9hte9xbrUcE87SvguAQGKFHkU+j1ggFWLh6rUj0/4zgCEzPcNSisNag0Dr1SufZEQW3qNBx2NOkWx/DTb4jqKNDAqo0Q==,iv:ACmSXu5cVv36hQuwd1FPZos+LnURCwYftAIHK3Jh78E=,tag:hMb7LpVJSvdpdQPSvSIHZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:vcc49EZZjV022NGmRzEKoqxc3NUkUw1TErBAkY6k8KmxDFzHLaGp4DbcXZwG0CyaUhcQJ0rggMp1q1Y0Oo28VdbMqq5jW9TJQAS7Qu5nUuoWHu/qHEjwXbygsB6ZzJF1IUo/6b8EXnsubG50cMrkWr6RX+GGRKnL320gPaGo6AQj0G17vClVnaPVu5Hoo9Sz5WeZkqTfx0Y3xsLBltxlaQDeuKQzrSXXgBQy,iv:1M4DRXTQrtX36GTmTIknenn1v2L2CDaK7Qvy6OSjtBE=,tag:SmLHqYKEJOO/DIMjPxOzFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd2V5RVVmQ3NoMFM2QjdD
            VEIzY0tTamoxcURXVjA4UWJSR3JPNjFDeFgwCmhYK0JESmpjTm9UUkxmSVdOUS9p
            TWRTWUJVbWlXZ3lxakppNENHWCtYZEEKLS0tIEFqZElGdGlnYnBlYWZYQVBLaW10
            dFZ0THpqSTlpbTQ2NE13Y1ZoZFp4N1EKR69EXiG0NmTTkgrYekVZMrd19uKftKx/
            nx0y5fbbiHfHrHiT1x/kJBaUJUP2W6aVGuA68kumg2cC5kbLjqr+7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T18:26:22Z"
    mac: ENC[AES256_GCM,data:R3gml1Fh9/ll7KpS9cyn9o0Cd+EMhEkhVZ2OwLdiILc9U/M8WficoD8fN95+kr1DbVswgdOWx0h+8TfNT5zbIlJppjZJicqbavlWxJtgOaOY96BgaP/cWjkEPCE8XhgPcz0Zwx8GCncWZ22J9dWJMX+5sEsHRD6DLmYS1HmKOes=,iv:zi+zf7JGaXXScUt/ET4mE1if8jhzsCDn4DAw/xy6xBY=,tag:7Mid7EDmT9kZ2mJY2ae42g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
