apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HbqIgCVXDoxznxG+0FFx8ifqujk7rSCVnzaC00FtnWOGomWHgMXtvqp+6W87UCJanYw8FVOSvppT8BFwHmOFM4yYyJvem9H/2FZrUrhwoXgcgRKvZzGW3gLsaQVIJYbPwZ3XQ05mNjhcckFeiz5GUu56R3sn1EO0lHb6tnhDaHEbu7YvF4stVlCRY0DK3nKRj/9pGnFvTP5AzQSoVlQ+3hz11FtykAOczAErKZKu0FPP+cqplbE7LOVWT1xFRzVvEPuJdpIvIkqH1SrcS4srz61GWWtKqTz63miBHAN/pxdY+uaHCD1Wj+QkDwYZcdi7t1312XmmDIlfXDfZHMsd378n19Le7Ds97/dugXoZHq+cGwm9aYclvR88TSpN7C+b,iv:x0cIZOk5giVQ0dFoAmX5t64PQ8s7I6F9Pl657XwJIrg=,tag:zSaMcFENezK2GNNcZahhgQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Pn0nPTrxhjjxk6F/riCX3sv7/DIgV3uudO9o2tf5/HWksnzvzYeQqM6scNjNv3++rzfG4SL+yY1S8XyYguKbwUq8lVJ6Wp7Ot7dgXPkGHoHv9zbQA54GZOlp/ODgmTsFcuN0+dIp0bVUODrHqF2MxcR8DzuzQr5SmEu7TnjvdpfTTH4tIRG7u9/EkZjOmLokmriRU6FrRO02VkZ+g6Lcu18puKTIv2LiIQimxMdl6wnTUswoLCIGYmvrzPY19Fle1OX5PVFjJzoPpbTCpw==,iv:JPgEW4kQMWL54SS1Ew+Vo8pfVXd+aiOWIoddKMv1bx8=,tag:6RJhnila/BEVjuIAtdjmtQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:T4pWXCqOXOYliHUrPzTDSFWSQSm6AIZqakoO07ob3LtVIqNOziH0KiWUAD9IDEvrdddwMVObPzifaLqTRZFShsqEwT8qJHTFsUk0Rirhu1asvUW+FQRDTibT6AmpE/yZKA4zK/1ePFsHEnwMEsrcjvQ4MihJvnkmyTmO6a+yo0cnlvGqWp4qKG3mbJx4x71yh6eMaARhoDjOatVfGh1oZpNXB1nu1kBBxHhr,iv:nElr+Uk0i2qLkiNv/ovyBtFzOceVq6HfT3jSrvf3G78=,tag:0jloHNsCPyaqLsKR7wSDjQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRllqNGNWMU1rTWQwWk1S
            RCtwdmJqOC9VUnRxZnBSSXJEOWRVSG1Yd25JCmU4YzJyWjdBYkZhY0ZYNG52dXN0
            dWoyczNxU3BiWERLbXZxSjduclZmVFUKLS0tIEsyTDhjeVdHUGkvTEx3M09ZanR5
            azFzUjlVakp2ak90WG8yZU9KMG1VWVEKeVraoFTJf8tZquMIDv0aLq+L8MF5k2pq
            66uWbkj16m8fFSv5Br2mEl1vHEJ5NTKjHXmHLyC1AA7PKSC9Z4rsbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T08:39:30Z"
    mac: ENC[AES256_GCM,data:1iqTkVGM9aqHMi++rGzFknIGXiBUD6t7CvUoJY/lCHSHlgntfwMGKYfhsn0mu/JzF6JfMTZS7VDtvc72ySrpDNm/DfvrAgjwR8YhAkYRf31r/TG0el4YWM1l5le5iMYLkOK3zkvwUSVUzN2Cni7DsaBSE+EQquyoVfZHjJb++/Y=,iv:qLBeRjMR67TAb02bfDkRfpGkghMV5v6qt8kNz08629M=,tag:FeBvPmyEEYiAN8BjZZSv2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
