apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hrAGddrCfbutPZ+P3xj2FhxjITMtjuLhn4vxy/H0Osq3eEej+lwa3gTztyeH6QUcIjiIjIGpyYC95h2gWukCkjmFUWWmFXUjFSkNjamgmmcXNBure1ZDCUnixa2hH2K51UH2q2BU9Yg2DHqYpAwFIFUJaOcQZS5/donPs+gSa4ieCHxqxPs8a/N83pr/2/NdNH4bOy7UuSPdUvVY5Z0q7xOemyh2r7Z1PF9q4Wbq0W/5ejJmPegOduXf/iBvclmo8Mxgze5uo5Vfary8wy2lZ3dIBqPtvtoCsFfbnQDUXlUFoo2u3MAPSw7klrmDbXRJPaQ733JPB9SCxx48JZXKo/iciyQwtyEHRhxTLkxDRkDHdXE9S1YRcvCKE2ku2Slu,iv:RX5zCRUzdR21fgtQfxOltZOdL+oaHVLvD6L6Scex0u4=,tag:u/ZxZhMJYKPJbz01fEnF0Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:KYrDUNRiLFA4mXzVHO927xPDT1lDwSyTxSLRA45lbkJMncuk9a5V3tEjjEWXxDfICRE0XXSkh1ri6QEslnvAMSil/rmjte1PDWzPjGqUs066w+AsGo8dgxjGZJiu+sUQH2/uDxqTu3xSb3VQgjN7drrvi2mCbedyFk7bNtp5xXroML94tr3o+0gyWxlxk7Qk0h4Sgc0FSzsgfHa5ItGL5v8y8agKdyV/rc1OzxbM8MesVJQLfi7N/aMeFLIpSSsSyxvWR7HAkvrVk1sl3Q==,iv:ucNJZJnxBEXzawrKCv8xM4ghY/fjYou7El6UWlAaNvk=,tag:Y53nMtQjEQSoe3Kj5SMgDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Y8oXsim+j4sO0PNJry8xJuRI4a9zkRrFdP3pBMs2H8XEBD4MBMvVSoCRAeme0buM/H4B1h6EHbJB1aadd2tuAdp6LLmpwznIAhxiUPl7W83bBfM1HHPke4l9ZaZFHx8gdRV4hf9HzqemxpTEJOaxS8FhoDRLiaHeLmia9ItHVOmShjJnpY/kP4J4tquVAK3DreI6RSJtWNGmqRJN78Wh1rKXq4XbqFaPHolo,iv:gsv3J9tR+Wgsrw/HPFIXpPnP+rVscRjeMebSYatvebQ=,tag:MOEU8xQIBkqhTBlfaDLQHw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R2ZNVG1KT05oQnJ5Ti9a
            MzF4bVJjN3R0WFJ6Wm9kRW9wY2xoUFJEWVUwCmpZdmVXNSt5aFIrS2paOVBGdGpD
            RFVpSHcyNHh5NlhLakxOeWFodjl2NVUKLS0tIFNMM0Ewb2QxbDA0YkNvRGMxSjZ1
            Q2lzMWYzMEJLd3hKUFE5eUVyWFh0S1UKrcAdAVsuCz06N4asgr3Iuav2vh+1YcjI
            RtXgs6FZwx3pnv5NPDErgyAJXzaJtCQFRJBdcxYX4S/ynHMNQj/Kgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T16:12:12Z"
    mac: ENC[AES256_GCM,data:PcToL97v3ll9qEh4skwKxG3EkC1Uh04z0W07484crLoxm0CEkYVL8j/z/jumTHt/ONtfGdd+mAOyS8ZOgX6fSjlJ0NLTRmT3wHYkZZvGdW0Nn9w1q0rhjFv5pQ/RVZh8HxSHhtwu+6gc2h6zevLYZ8KNY8Ok337FztBbmyzjJME=,iv:9fsruXtiZ5TpDrFAFXQR+ArIYjJMANpStyzLxlzmUUo=,tag:rNwJuY4O3anJUJIBetgPnw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
