apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IH5yFHeXi/2arOLG9ELpVmv5f/tQyFOAWH2bFgnsX68s5SFEr2Rh5647TAraWOiQgGHSXrqsjB/YMfRjI0L30aPw5KG0ojxk95A90SuoZziAZWfGHdk8oV+dBpmXdjhxckssY55DMu3yVw1CJqhcbgm7NI36tuqvrkJd1lu0X+ZAeGklNagPuekbym91is4mC9mEpbAV1NNYngGHJdXVKO1YPrVmjsxqQY2nSZ6TLaVwoPAswX/bG/4tYgWQcFD37fY9kwgB1i5mdYAjlZW0mZzte9+SSouYxemQB0HKgaeYusdS6BLTOE8p1JB8DxztIG4HzPGkr59LroLgD6kOeccTjamvo9QHXviaz8q+xMmIV2QjaJcluUntGv0k+VCB,iv:JNCNV2I0Rq1WVT/aQf5rffNPtSkQ6DlvmeE/oZd7HS0=,tag:Cyo+vXbM/ND6ZIgsVAiqcg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ltn9u0Rc5BlanFBwW6XB4Vf6kneCv5HqTXpoazUGCIepKFNn32WE2u7Xl0zCFlBmHbl0bM9lKBQ3GE+kCvNhKuOevZpGrGjgKdH6H1pFfEnqkLuwZBDHgMG0xcqr7xrOKAb1mIjYIyxrpwFGKkFk6aqMis5tG7U58Mnt2ER2ySXyxp73jDsmLGuXn6MrhTDBBJGqTy4BHUmLp8JHyCN5dg6x3IxpZpeExL/09pDAY9m7IPhIqfExm8Wy3Ac3l/4cwSE4n+VSs7KHl5cVZA==,iv:g1WfFUiaOFsLEF3f439B+Gw169Wx6ilsm6JmuyDmwvA=,tag:UEfCioLS3vh5M20m70QSDg==,type:str]
    known_hosts: ENC[AES256_GCM,data:gwEEsy/ZxvTDxBlgZxeoe26UkDJzI/P6U9No3nbPYmcgxjK5gOzL77LXi/elLIcEUkwMAl7r4bcAZhabZ6/PjwEr5NFIfBQImF86Ckr+xBE4VWT0ozaqB0fFB8gsvbIKQQeDj0C5CA3a5XldGNN7yuG8kKdPbwgX4AmFdZVmLM7AYW35jQyqfL5MrkgvmzVzifoKApIH4gZ92OJKA+csS0b8+y7Q+SF68pji,iv:7+xKol6XK2PDgTU48+B+2AZW+isDyphOhxR0v40R5u0=,tag:Q7aCb0YlTBPtRGD0v1EYuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeEVZSHczeWd4YmhkRnQr
            YzhoOXcxU2pZUmZvSFZSUXFtdkVHdVJBWWxzCjhMa3oyanVyUTUzV2VnNmtTWHdq
            ZDVQa1A0d2VYY3AzNXgvRGhHSFY1THMKLS0tIEdOZWJ4cE13dDc4TEl1ZHBadnEx
            d0RDSkQ2cU0rQVVlUzJGVzdBYlFSNnMKdyQqZFIyfXAuw9qeHaUb0FtOZgX9oP2F
            xOQv3rFutSUGZyvLeSTqa/qsHoVOXT3/wX4gEimVbGXccgm6wZYVSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T08:47:22Z"
    mac: ENC[AES256_GCM,data:2hes6p5V+58gpE2Df/2I4tqfRBPGWgpuI3pDMDd1H+xdNt0zOYX3lvxrTVNE6pea5ftmE4PEjhbKdqODsbXVjDDEJ0zPiWogi5e+pWVG3gqDRH8slrOd8qeKEPfnJmlruS8CC2trp+skGZ3/vFKX6pD9rpRcOTQFIjtcdtKVbuI=,iv:hR9vD7KwuTpL/p+TturYlnPYVrfHVXbSS6QU0VB0X6k=,tag:kK+oECSStYrKGS5EJmo3WA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
