apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eqnJqk+JPFP7jIR8Ump+Pck6kPTcu4fCaePFG7MkCJvuZlPDRf3j4Q/Bb2iK/CU04Jqh11NWD4pST9T13zvXze8bMYwz1qn/F1Lq/V5S/1AyWR6GF7iQLl+h086Vsb2Tfi/GbtMK4K+lJwx1SBCKi8n/Xoo8LZie8+CI6tRxFcaQm2LIeMsYoIraTnkPjKQc65xk2cxytiqEbYV4KtNLYArVgTYS6If9LqjI72A7rdJqPcAjCI4HzUn8fUH9jBRMtXiJ2w6ZafvXmb8BvJiFml633I55ok5jALwFVjZt9fCo7KyR2QROR8dwmgaj+WXpVpW6CTMql81qgGf/y0stcZ8Pp1YQwIQMDLoDFhdZ2+UWtBosdZ2uQl8C1eJoP3DE,iv:cop8Bc0gvMOJEdOui769pnpXe2YvuvdUo9RUih0W5ec=,tag:guzcwZ+17Uw/0MqmDWAaMA==,type:str]
    identity.pub: ENC[AES256_GCM,data:pINfEGU8uXk7I/0PACFb1OEP6LnQA5G6B3au5sxR3PwPfQPiGa2xNttFBfiSFY66ZCXhn+4YR4YdYom+V/c+rjKkTFEUooESiIN2qyuRYBlrwaVI6KmwQZTOMZvyMvfg/KssUaxtSOZdohbSxvpwuOpa+1SeGXpttX+KxOwP4Q7hqS5+HbLXuTkt1CTGM2t4BqEtQDvMPiLFFm7xfYpGB5o+l5yaXX9fwEyrphKylIpR8TfYF1JAgBGOOxrMhvc+LCzmdSJZ6iI6PdYpNw==,iv:VyooNn7uZJwOp6Tqe5McJ4rJoJuGGgcfHf+Z17I8148=,tag:EP9ixNNhiJfnUec0ZDfJrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yi/a7IoA6A6FIxBqBoS0IVRCtO4ZLMmU0YQGk/fjT/hiHPv+KOasdbDX9bKb+MX3IivV9tIBtpNJKCydqAQcwBvT5wOvOKnCXxjkzvOgKyW9NugtNu+AGAevsZI/Xeu9EfucNHER2BdV42qFpmUWQQH8oAimoGN7vTWXERsFSpx37iR6MOYTEtGwQDfTx/z6y4ZH/PkQCCCX/REMPIVL4lXV0xjYgaNVQxG8,iv:avsagSNgeY4WhBXBSnux2nEMoWTzN4Wi6WNaMEQDDuk=,tag:DBb7wTADboG+Q6ZOIAQ7AQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUFVTTVU0TTZvZkY0WGVx
            eDNkOWYxT2dLNjdSL0pRZ3I2U09oNnkxOFRJClJHTFp1REVVV1VMeEFXckM1Z2ov
            TmhrdFVHV2daKzJhUW1hSkRRdkI5MzQKLS0tIFo0V1NPYXJSOThBVkZpL0xjYzdY
            bHNsMXNrV0NSZ1I4WDNVcmR0NWRBeGcKJ5F+gaWi2slXGntoSrbsB+K5yYrGbryZ
            n4IVrmk/qmVP5KmFfNP9Fk0aBN6ooElDsXmolD92dBq4ztIUaTga/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T13:47:32Z"
    mac: ENC[AES256_GCM,data:1P50o0fG22mKvdJrxgyKTaS+XwbUoped7wEV+BjJI9tQ7rKyKtZ660ViF/I9mnS17NNY9zY8qMl08wXDdvo9Aw5oVxFwcPZdWutWDemNKo7mR02g1d7GbABJAWdDWVmm9G1AMHKiAANb6+uTy4Y2afYDY+QSXTZAZ41wxw/cseI=,iv:XpPawz9UoRq0IVKLzSngsuym73C63fBCCKEQqyhFuDE=,tag:1cO8/l4/OjtlkRY9U7ZogQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
