apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PvJhkZLYwVa6uLRoWkP2aOyGnksxeEJFphSDj22EV1Vhwo4aHl3QoI+shHl2Kk90Ob06jbnfXI+VxAGH1+6u1MmOPtOjhh13+zGP9L4HeAvMWNnDYljxK4nfO+TZQcSTvYGoCOG0ch+ecUg5ldvx0S4OVoXRZDqlV6wVzXqTpBcvMx9y6gzczgz5EA1gtH+RQwlDVOMUJW0CezNyFtaQ706DoNW5vfLi8qrQqXBelMcY9KGe9Eez8hohzQ0CDw9f8qUnbi4S5bb0mCrkAb+2hM/4W+V2WkTxZ1a6V/0S6y6QdF/PJG+gW42Kat+AndT2pyKTSa/HOiAVOxw0q4h9fgwazM3FbJDHVLww4WorM3FFxkKtIYIivqjaQIkQJa5N,iv:pPomjRFYWszRv7G3AzLa0y/MS8dTW1nnV550IkrQy7c=,tag:IIFvXdkhmd+I1Qzuy2fecw==,type:str]
    identity.pub: ENC[AES256_GCM,data:MYCbG5nsOEeoWLPKC8DoyzCmjkqUTU2kX5hFTKydmLvplrKFCh87AYlb/CSCLT986QiHSbcUzKRJkIusA3hjjAJM84nG+YRN3h5SickIeagbBcPcFloOhd8VCGCGR97yhWAJbDfpnKLxivIoG5fUBizNe38RQ1E4WucDlZnLP2Xgc/pxo0apzL8dHypOHda0qvkj9IFBEeWskMVn7L1bIb3BxdUn2zkdo6uxcVdY7YwPhf1GNdYTv9kAIt1My3qFjbiweNwL5FO2nXRQzw==,iv:1o0Bzt+Czq153ptL7hnBfOOu2g8fpDF3R6VhRmSzZT4=,tag:ROKWNfp0/dH+eAieMwbIfg==,type:str]
    known_hosts: ENC[AES256_GCM,data:W/4G9P1BHgkJw68QE8U+Azoql90aqb0U2QNCXOQj1ECfbYwWpO02bwL8Sq0g9Mvvi5mgjuBNruAguqGHIPxKfDc5LLqNNdpDNJosgyYBcNmXdt/U0DK9BgDFc3Xc13Dv1ZozU80PdpBHA+1RzMgLbdMmAaUN0h8LqhnSGRMih5JI4TvL0c/7XrjwFbs/XeUOmhRGSmKjTnAatMPIBu4SWKoeXWACz7X2ateA,iv:J8jhmjSHalaSVvMpLVa8rN6hn8BuhF2adUESNX44Kug=,tag:BAHBZrmNV1Ezq2h2zXeBUg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb0dmUlEvcHdLZUtqVnBW
            bTBkdHJqeDQxemxWMWkvV2NaajBvYTlaQjJnCllvd1ZmbE4zcXc2N2k1SVExendt
            cDd6Nm5sMUY5dWlWS09ScWlpd3B2eTAKLS0tIFBER0xDSXR4UFFZbVFKbmV5UTJZ
            Z21BS3Z1K0M2TEtxeUVuVS9mMGl1aHcKgaMJlnNEcSnrNOXBHeS95cjkc4JMbDGL
            G0EQxEfMlZFW9CPAYuUMDJs3kfnLI3rhXtp2r24dbmx8UUaCLT2T6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T14:39:54Z"
    mac: ENC[AES256_GCM,data:Lu45cB6fURb6fvv651++bvQpPBpIb2iKy3gi8jPYToVi2uDijVyhM752dl9lb+BliOuFzJQ5Xt+ToHBeamotjyYMjkMEXrwHPRbGqQx451qOLN8PlHhGKg1frJa2vQqWSp2xAKLX2/uDqhAqt9yHplrxMcXMCbdReKWeShleitA=,iv:K/fVxr6Qn6NRInRQ2QN9ia95JwDjl1B6pqZ39b9zU2Y=,tag:sk+8Eg3bM/pD2Sx5i7RbzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
