apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:I6NEI6L9Ji7oLDuQgOYT3kreXm410OQcdjHMFaJoj3k3J0PD2t7STKLvPnWpiliDlmn8JU+L889xkFrJeqhHJAjPY8rUHQncXw9xU6awgLwz50p63emo2ZG/lYgTABpXdA/h71JCaKRf6tyun4tbo1eFX6nI5XeSxQAMlICMqLD7bRMf/KL2awj0gVrXhi4K5XNUYJQSUFKdm9YVPpAV2S7SRAOQ2YN/Q9rrr+wQ3xo+nWhj/1gnK+Jvgz36Cn8y0/06WQtruQ04YihTzYXKIqebIVChfT2BLC3gEBvpFgup5LqQ7R8HgYVseHoEnPNCv/yVeQQ1XZspSRBFeUfjGfuw0BqplPYCmyFDk6td2BMskJ4daoI4b/1+9MVQT2le,iv:LnQwkCfQF6VlwMMlcFPw92+NEIeztasHQlWqtmHd750=,tag:XMyE+Pl+XDforxEColrbeg==,type:str]
    identity.pub: ENC[AES256_GCM,data:irC9p6X/w0ywLtFjug9zWDasdoaIuMROnjvKbcUdhB8cA/XKH/hPcx0Ub99CLgoZPyUpZXREecqDwpPBilH+hY5wanByEmhJee/UCt9A6/d0DoTynogpP18g6svMKv7yeK7Six6aSivxTAaAOOcpEPCiUJ4hBHoXkCyqWadYYwRGt+hAYSXBUJpAXU+6I/6fdEYAc0B1WZ100EVMQ0NpW3UPGRYcLUGq9Z1Ev6rx+oIkZZP+xTJivhlpbfKDDVy0Kpx/RwNIktDAzDyJZQ==,iv:YnAqnM6UWaik6f2UIQo3NxFW66QyD1AslghGp9B5e54=,tag:jqx1K4ekHNSb+zip3P/D/g==,type:str]
    known_hosts: ENC[AES256_GCM,data:wDJDj8UwnM7Hzw2F+x04BDirYVphD50/EyfdSnpzaSXg4PUChwCurzwlWyx/OIjqZHfVGHVVqTMpl+Q52Ca2Q0j98pEWg54uGG/LT0QTV8x1lH1X3dcZ7S+J9X6W5hZX8uNPaRlgzeaTbPjeu6JVtbUsk4JilnSsdLBQNBLOFPf5zcI11N+B4HqhWmsObnlgx8rs0maJ3iDv/g3C3ibEPDncPfoBkrPP9mVu,iv:x+eD2/X2xBasG+MwIPu0XzP78GcX+Ez6jzDdSSrgh90=,tag:W7YvP0j/f0FlUpk6iPepLA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa0RyMG5TdThadGRtY0Vl
            dy9hMFp2UXVPVXJibVE2SXFub2RCN2w4d1RBCkduZXpDWmRNMW94RWhPQ2FnTEFj
            WUhzaTYySWQ2aldrUjlueHlnL0dxbUkKLS0tIGM5VXdVWVhsRWhZU2JqNXJta0hj
            SzI5Tmc1bDJWeW1ZZGg5OUhldENocncKybYpJFNOulykloTqx1A5v3E+6y0Kipe+
            RwWxbknNrG7anU9SfdwZ0SFcTg3sA0a5WJn8wibEb64kpmgbKdx+CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T17:50:53Z"
    mac: ENC[AES256_GCM,data:rVk1kvKqO7eRZUwrCd0ygMwEyh2LSsD5khC6eHTrGyiCAGZEVfIYHs4DwJgYB5++/OaPtf0kv5jrP+2vQoydRWUwWPq/w4l2YNS1eUZ8JNOJtdjslF0pRU6VEOwCnuLdfR3ssXlQZZwO9l/EAqalSxUsbAu1UlmTTDKdSgd33aU=,iv:+WOD/t8JGx+u+DXPm59duii8WBo2Yg10WD+j5Y8EDr0=,tag:5Nr/bv0fhqO/+FukdaazWQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
