apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5DO8fGdp7Vq5lIWlyaLjRv1O/E/WUBiGJsgJEAMO3YRz58u/hjIxGeAbvrKEZ/BQ8Cj5VnGhZ1i+P9Y3fENeaz2U4BSYo2yeQ3DOFY/QLn+1crID2Uj4mKUPIjc4Ran4WekIY1D61ScXdUajgJsj0zBMJk/8zAazwlkV/7l9xJor4NgyYxrVNim/JdXDX253qftldvG25HNKoCkGxiJkTczfvIqN/GVX2p8Xmuzs2uVmi7H3RBK09eP8KOFPm6zPYZyvj5VVHEA9KjnriZFa1sSNHH9Ygx1yctVzQX1A5qT9woJCZ/c7KfL7nFFfF7UQdTxDH9NDd7I1lbZXoKkKLbqAtPDrgjkLEaUXDAzshUrpBuNK4eqqSlBXxv+9Rnk/,iv:GUoEOKB17f8LTOlF8bDFcrzs4i2rmwvwOd4VQBJiDEs=,tag:gMNNyVy/5/b7nwzeGJg7TA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8U37jqJGTKIXH55Cv8/NvQpb8CuLo73kdQikCTljVbWlSFz9e5IRdXkv77vMBOjVtBT1UIizRweUSiCye4senO2yhV+o8FDIZXIWmmOsNf2la0yppaPbZ1kVYVJazC32ShccyY3ZP/7LYwSVerxXzkqpMl4p5eNIOZlV3EkypY3QXBa5njATdJFkTK1ogIRcddbFyjjbRObRqAEoRSLm4GqGUn+jIdGysss4NvX7udfzmnz8NNzHZ636K96NAgzD65Slh7sSgLBtxzcLbQ==,iv:h60SMkyp8BZukfRWZp5XN4DJEgpnfHlVMVq7PgWIP+M=,tag:9k3jdPbdPcZpjYFdKRxxYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:IfbhZd8ITI2757dME/UGSYJZTZ6iC8ES1iP3DoyoDS+rN/uiCDvvlf52Ic28QrJx/VUIMOyWhBqT5ckRi6ja2jGK4YlphR0qDIHbuqoYa9gOalhMRqnqMKJGYaHgUHevBA5X97lTvjpRg9PF+wpzUYktzkGAxR0RAqOyAHSZMCIpWhk+zCj38u/JV395rB3SzYF9p4sC8c967ShWiGRNOAtBB2O1svh3GmPs,iv:E56VASRym//xmiZGu5KrJwRnocAeFinLio+x1SMP2ak=,tag:xWo/vR98fq3WLGIbw2agIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiamVCbCtJRGFON2lFMXRt
            cE5NYWxNTXU3YVNKZG5ONEtSeHVSRFlGV0NZCnhKdUVRdkVSUk9VTTNxRTFUTzc5
            djd4ZU9KVjBzZnpodHh6K2xYT0k3UmMKLS0tIDZRc3pvTlBjaVN5M01qS0wvSllB
            aUlPSk9ZKzZZMzllbVppdzF0UHQxMXMKl/SKlJOxlq0O5r+6/SwrotMzKoVUm9YC
            /lgB8KarF68byafdqls+aozjUxDrFzGRB7u9dT6glBe145cVbiye9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T14:37:06Z"
    mac: ENC[AES256_GCM,data:Zp7y5pgDKAVfXrcWy23JUMHfUZ0pYHIDedCxYNDkqEP4dz2LXgW4EBIY/wDJEAxvYHZfHUj/Z4VDwASiUa5Wl01qglYhQBfsT8QHSpIHPPZnxzTcbt36EwcLqwjIRO0VR9XyiWqg3SIbBsYtvzbH1ruUiNwfPVBVacx0KW5JOts=,iv:bdBvay3XnvRXa2bPfkEulxKiA2OPWJNY/rdq33w9+bk=,tag:GQizLGeGyeC95CwzPddKbw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
