apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:H4HpO+IPOjf4ongvfWb5duvdF+1EG9qFakV1Pv3SGZZenOw2Zk37PjS3gmfGDtk3VuGrnYghq+tg7RRKBfjUQdZWPfKCaAFM4mfRR3r1kqvIuhlEkhQ8nICM93aN4BF88bm3gMHlcJPQj2FG0jgtjdanT07wbJSZyz1YEUe28VRjp8vJI2Ln2lv7k6ig5kJUxYDot1a6wVARexnrvEg1LIWbSYMz02cZFrWm+3AoApbzaA1TI4fY07osE33vTDBZ/TWbsPu5DQiSy4PDTg3QAupmr12BvzybVBsfnLTHRDuZYAYj3Y4N6sG5Vqt/k2rbbKzkLavjI2AI68f4vusS7mmRR+3qY6iyacAqNIf7CkX4FvK+R5oTrTuQL6LL978r,iv:5S7pdWqDnu3AMvTEzSREdWAKUal9r4CL5oCW6iVKQRw=,tag:S49BOItMmRhe7ukPXLiMMA==,type:str]
    identity.pub: ENC[AES256_GCM,data:4k1o1uiCkrO13MhPVi/dqynB4va04TS/4roBNPluevZoaW3jBa6f2oSzFug4k5V+VXYmPAciXjgCRfUt3ayTxXNpU+ByaCNAwZYU4V+Xx2N6hLeya/aRHMsmFIS/VUF7SeT986BW0V1aViz3dcubc4mr/CglgV+jUOXO3zirE87fPnnisrY7VjSgmXE5Z3pjLFXyVt7oS5FhNPf1t0QdLXHJI1iXmhxmClRONbVHp1VjWKnNXEnF/74ocmtVvwyWLxsuKeOBwfjYU9IYlA==,iv:vlnK68VGQ+6RfhAfumBUBovFF2trD2bcgN6Zvr5exP4=,tag:w01Q5tfHXj3m0xgJAfQEeQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:XHRhGruTpGRL56ewAK3WLOyb7GisC3w9BDxbm3tfZZsktTOodQ71jF5ksZMKAplMXek8EVyE3rYsiFCrU27lD/OYyQmQpgC1ujJLtb3jcDcE+aBAg5bn9e3q/G3XBaYtgpQx9SivkLSQMh9IEXWXxjeZxcMcm65p2NRiA7lsNKbl03RLoM1n1KT+joFjIPvX3+JtJ8mx+oUnGiwZiRsENurR3hHate8fxz5d,iv:UUWxjloO23szwGxzc+rcLlSWtD80qfM5cydBt3dcQ2Q=,tag:byiW5prlHjPG5VhUF+GOyw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NTlqYjZwVklOaGtFc1h6
            bktDZFBJNVpMeXJ3dXI1anRzZVJvbVd0OXgwCjBIZTgzQ1dRa1RQU2ZYQUU4ZDZn
            RVZ3Y25BNFFHUThTRGpJZlJROGlDTWMKLS0tIDRjZDM0U2x2Vlk2RVU4WjltQUw1
            SkVOTjhTaUJEM3NhbmlOajlNWW95NmsKGNuX2Qs0NbGJV75H9okLZWW1R/i3nsob
            FBdsYuf2VnSUb8SL3ZFZSNAbRdpn19H1HXbyK7MMXSU9s68TEHUDvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T00:25:23Z"
    mac: ENC[AES256_GCM,data:OPLWWtnfmXnMU89yKEGwtiI92nofo4wgqBpnNqOgUQCVD9gPTDujcj3TicR/18+UrXwksHwoDz03gmHGrF9Wq27Ni15J6K1TP/m7YjT6VkZ2J5oZcVifT+mlOfwY54n2aS6AY0Qc68uQ84mQ4wlHJTg/kEmhFyWDMrqEWzooU2E=,iv:nRooTHT+ExPRyWxyAZKGcqXc8l9ek+BNeLi8wZ+LelQ=,tag:6LjV+SaxggiTLuPRYKn17g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
