apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dopn/CvJH1sgkCTqVj4r8j1JuqdWyLnvRW4zP+y4w9BGrgbYLBH8bBKWsrDtl0OfBXYJjTlkNdwuJZXfFxDopVd4CrhVBpxVTKErqvsz6VxSpnV3j3tiHt8R3QSPJ313mloNT23TJ+aNaKlMKEKhzr3z2xDbSBeOhCzKuVmWnwguyXVSSQB9sBiCBa4pOpa1kwznc7DXIP+EIqTM2bHWKQvmofsK0mOKg+61k9OjqhbgnD3lFGWw14190H6YyZAWtl0ewDmpRa6fdO9U38Vr314XT4gjiTUKEtn3ajmACakumqmfDXOOaCcyvq4ivc13qO4FH2zdG+Ko7C2hiqG7x1j5Q+4fGFBDnSeRVykVuPTEm48bWuigjry3a5gcGDQz,iv:XLsoe24I11fPrnuvFwi0qqbWcWGP52pSY0Zj0sH0ViI=,tag:IxcRNJkJf3oA2jsDdCM10A==,type:str]
    identity.pub: ENC[AES256_GCM,data:eoJaOmj0opDbodLK8XoVZANvLJuXoTd6/tNNo9o4U0sJw4fhLRywIVLi4s6zQbbiuSH/Wkp0I9rxYa2p7O0IlbuymykXP23IAgHtflhLK8qgl34dod0QWc38N+UojbPjiu1QtQuLXE0r65dz6MH8y7EXXlv0gxPuyfnK6loDbo68Mda4z3lMOxJHnLoGhFMmizE0dv5zEgk7AxVI8cctq6kyxqV+LpG0Z5BP+2Jodyt1rdTzdwITEuaSA4rGt62h4s63NbQwtRLT7OC0iA==,iv:DLtUfrirDpLpU/HLOmkBsdCb8M1Gczbw7ZPkqhLsif4=,tag:5DCyl80h56+osxqcomldkw==,type:str]
    known_hosts: ENC[AES256_GCM,data:yPhVPsghSPLpto7/clNgFGy0fru/EMvmY7jkZNkSnwxxbbDT19W8Fh2OUBEBUeUwfA+HNOXxFl+91c5Y/uHRC5MAU0biqeJ7Ju7YD4gxLB7qsWebrePbElxknB7UNhCRdtHZwxJaX5KJAq0DwO7K+ViVvg+WX/n75iW3wMthGfeqXOmO7m+4ZqSujGDoZlUIWBn6oy3I06R0a/sNhOF76WMv5KDJG1ztNzxg,iv:MrQQYEebBdfEZNHvuyE4NDG/OCkjjjAhuyXxNhhB4fg=,tag:AyQvRfj4RmTRiFj2ueIoGQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K3FDMGFTVVY4dm5nVTN0
            K1JqUkhxMFk5bERiTTQ1TlJ1SS9RcXVjdVNrCmQ2dEx1VzBEdGIzS1JDaU5lbytq
            MG5FMHA2eHg1ME5hN1lJLzA4aFliT1EKLS0tIHlseTdjbk5jMTBFZmdSbzZiVXZ1
            ZWN5NVRtci9DSExaSXdEc1ZvL1EwL00KEErgNnE2AeuEZGKV9FbJ7Nl9mYm8kOaL
            Mbtun4vF72z7VKC3RsN7fAZVIsx5XLPF3P7+waglevI0gy+y48KrmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T14:11:36Z"
    mac: ENC[AES256_GCM,data:IE2/itC3t2vd2A8p/K2ZUPB5SweTKM1WRDVGF10s2vwv587Vx0S5qorvFmTMx9b6cspHN7ADFV9m4mwx68GhWH2lolmMxLqpwl68NMOUsziTdIa5JN7O/uuoqhiSfj9+Tob8lswaGpLQxp1afC9d9T0rYF30YdZJsZ930yEKYq0=,iv:T+U4GM7uz8lpPdkGWHoXcCUwipMACjhmTFvKKQwhAsI=,tag:DJugqSLp2EAbYXEHojqFAg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
