apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:neVZ34p5kl8jCwPDnFsYR7KkMD6fT0czHnd1LoL5Z2HnRrqf4HO82OsIo54BHwu4mHUDeTVe4zc/5M+bMze0c816qaU4c58pZ/8zBylvydfYD9ilw7B0Cva8to+ufA11YVBRaDWJFEaBSpG2jVE4SmmO7CtkUvV+20jycVH34uDpO1Ofkbdi+s56jk2VJq+OzQlU8WbOjBOUQ6xyX/4W6ag/KphmQU7U2n2OGaE06/xZu9fEfr5WFWrB83jSvXvccnizInUaqfrjS8/rlTKJLYapoWXI3qTXf74C0bkzf6/saBC4Uvvghs2NtuB6kJdPVNgJDZipQlFy5XmQnqypXjNJl/trd7Qh730rpM856V1014crYHfTbDb+0GQccTy9,iv:XNznT4qemnevxDYulH4ODUK7EurEWDI1JyEiphf5M7I=,tag:2EMBXeNwbwPkH0TWNl6Gxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:KiDu1yom8GEvUaQSIRizTzfCYFzKw4x4ygR6A9HsUsqVUmrWyHtnlcDmZIFtH049Z6Xyp7C9emZ2BwlB/duaUqoq0kK3MvPMPZbWGQpwdB/LObO8gkJmaiF/8OwAFiMej4XcSgBwLSVIfYuGq4wz8yTwEUJVdb7K6lYS7m6f/itu+/r++Gul95/B1foc/0vD7CLw+3TAp4To7WQvCUGmPGUr6HJev6swH1X1RSqMRdKIupo+ZbLRS5n41GkEILMkUXeq6Bp1EGehpNnMww==,iv:GUSov4Fy4wjZNjmEBYlT5bN8jL5305yjqqCFp8W/PKA=,tag:1yAzrUiqX2sa4iGG1Qcoxw==,type:str]
    known_hosts: ENC[AES256_GCM,data:8UdVXTf8LkArOAWaS33IjBtXPQQd4hRCb9tRz94ZgKOzUYaSODxcB0PohCnqD5eVJOSnAdm+na3xTYtcoxHkcUIMSxb/clgeIp8jzLR2xNZyVV3miB92ApMFGt9yNrnxCIwuukvoRdferH/RkA4+NY0KHMt5zC2AHZ5HlayOGTENiDUBCRhkdhSZs49qqIkP1Si6dLmh/0Uy1W51Nr9tgNaY5QiCp7cmzTZv,iv:3VXmlrvPSstdDJDPeTwg8RaZA4OxbB1sn5wD6JGtKvE=,tag:KiZGJWl3OKu6NTouDF+vWA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN3hKQTlaYWxYRXZ0TnIz
            dnVkb2NXN3FWZFJvYVdYdzRMT1VhZWl6L0RzCjJiSnAxZ2dKMnlHUGpPRlhqaDNr
            NWpLYXhyMzBXTklOWVViZlI2YkdiT0EKLS0tIDBZWmtTZmZ4bkVzcENDS1NuVWp2
            SS9RaWpFek1SQU14NGc3S3VpRHVmTE0K4CaMeHJdwmzTgMSODIUyJPVFHRQUwddm
            rp83fxrSiBpaKxDhKH19zM0XDSKlCN95UR7cd0n+0EuAn2a87k/uXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T00:31:23Z"
    mac: ENC[AES256_GCM,data:mZ6LpwVycjjx9mdln9KlYSZEVXm/sQqOoAxMcWOK+2lyoN+RQ+Gz4Q4nAuXyWhj9Ui6zvMCNtVaM4e5I4dv0b3h13Yn1h1NgCN5vuHJ1WDKjEeYAyLWR9C9w9Ro8hxISBblQnmg/xyJye47KLS9/BPfy3gw7ofb67KidsrPYPOw=,iv:5hPcqi8UnsXn6dwzHI1HkX7RAjP9Yr5NIycV9YUeQ+c=,tag:HT8UccuxdrH4r03Jxnk7cA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
