apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JWb/2jt8FmlVKRPBN78WaCIVfm84pv2zUngVW3js12364N5lCqq3MytKyWGnPE3UgB/D2m1QUgRdUM9xqAZnUjx7rv6DdaKvjc9gFF5TZHZES2Cb/Y/wxgUJbEct50XzKCHDav2yM/G1lZc8ZWqHVXqSVEmB82oM8v4m05l/Huscx1P9fSh7IBH72xgaywSjkXFIEomL6ljEs2b3zHHWCe4T2LpClTWEbv28EXs0XRfqjzl0S54aBqF4zBqzsPfVPIx1G8By98oN8OqCdYWxpZNK9IZlOYlEdXvM4SlpJq4AvZ9niQnJXd8weB8yWulVn0zzlywIb1IPcmsUs3Yl643maYrdUfQCfp8LJFEfLpcKHmAWho8uGeq/jt7iW18O,iv:xBC49+swFCS8z0vTg78n8ScHEh1n62bhvFvw5rmA4KU=,tag:l7MJ0sOHLzP/T4J3OWftRw==,type:str]
    identity.pub: ENC[AES256_GCM,data:2fvEFlzK3i7Tqji93RAFQDI/OLn84+FkoLNKIN5c7iMDFQ03Zf58t9fNH7iSCJLhedzSOHOVAAzxDLQfWUTpWMv8QLu+SoSflTDINWn0HzbZRliOc1B5vw2QlWf+8ra8lXkxlYR1mD5W6IK6k5ginpJLoajcTXPQh9zi+5UZgfKqqYzeJv8zBHLNwoenCYzxl3qmrLbq1zyv4UG8pN2vtDy8QgWB9KLepzw45M8g/f+0p3GZWtb+fs9QMECC1yAffubviXhu2A0el+xw9Q==,iv:lkFvwb4yFIzqjAigUXhlkzCTImlQ6rb4LNP/zGbtXz0=,tag:WDm6mqVH5UUt8erVZlTZtw==,type:str]
    known_hosts: ENC[AES256_GCM,data:+p5l1sB0LzHXM3UZ2KwhHOgXEePRryk9UrACyVBBTh5gvMni3Hrhe/thLW66xIWzSqLW3xp7Botm9JDc4C3BUVGyRfx2dxtJUZEhikxmKyEP/N2TPY2qv6T+EX9EczNaC0qNQ8ykAsvdWxxlfq20puXtlZ2n552MVoZVX9WgHYeRLnnoGtK1GhAhT30DPdXJfdeFyM40LgFg/GwH7KjxCT9jTLgthQ3qLhLK,iv:4TwKdISBKpp02ig9On5uP1X0UnOYnrC5EwJkMOFkTjE=,tag:IZDfeW/VrF5NYROxbvwKMw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobVU1VVVkODEyTmVXL3I1
            Z1FNTSs1ZW50YzRKdWlXWnI4QW9yT1BXOEFvCkhHaWs2R2hQN0pqRXREUkdQYmZ5
            ZEVQS1p2R2NjS2RTbUc3THZYalVMZUUKLS0tIGVvQ1plU0dycEo1VUlBdkM4dWc3
            dStaOHFnekFqK2tTUE04MmxuV1BlbDQKqdkx3i1S3FdXK8Bywe1p8FDKJZBhl2h3
            hY3X3weZqNTG26XPYSrK1uboL9JxEBnFN7G2DroKLtSS+v4my4JONg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T18:00:29Z"
    mac: ENC[AES256_GCM,data:gxbHXNDBQaH/p6LvPQBAPEizs2HwrzheM3DMz8Ot3SyDmiITwusGhSjDAQ15/j8F+UG2fmFGJtWDKokVo2H0cndDurWCOxUHTUUNIDxPZL94JpIfXgEhHEK8p529xpCvXfiSPOcpEMXW/wWf/EbmnrQ4qUsKRSz512VgFbrgE4M=,iv:uF6V01ghVhCFgiW8ua66vrXxHCksh9Zj/tSH3csWYbQ=,tag:V4HKXtRGi5lsRlu0yLIyMQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
