apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fvRvw/+8nHy5zPYeCmFKNNY73pkyAtWrw7rR4YaR0Azuf1UsexQbom5r4qXWnZBjqkG5+BDGYPjyEJKN7oEU8vCBnpHQKAqN5GkW3hJRy15+XQxahiXGB0AeDmAqrm2bLBTk8/KVRgHuufsA/KwtLhsZLd6xQRWI2xKIWhTQGjHV3V2g4pMenZKyIGW0eABLLV1RA6i1OHWzO7/w7kOHABty4qoBcs/SjJRQIsveT5NVV3yg0m/vK0adPHdPSG5YNSs1R2OUKMlkix8ZQaLOSQ+Tv/mUd61Y5xpnJIUPO85tm35vZTlFVLcB74QyrIEZJ38wqMeDn+lqBzAjq3lKIABEy9FigMaJP1QJp4VqSg1GGboBMkc6Z5C/aOAEzrbd,iv:7CyqXHmn8mBn1D6mvBHHzqCI5G3ExrpHG40SO4AwPpA=,tag:+xI+GZIb/ItuMDXMhKhqJA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZKsPIG8HOvZjuADSnA9oOogXVL/PV6FhQSUhewh5Vlx7Wrew3p6ivjIXYVBZk7BjPosGBtIIIa05mSfQd1DwfmUcM4zcDkFX8hhp6Qfs1CI3ANJIW6ZtNLkg7UkkXE/5t3M+6wPV2w61tBUCtp/O2sqr3bu8h1vVvHeIJlXrYSI3wyNO7j3qKbaNjoFcEBOU1QZ6Rdd4Z7lKL9oswQfKxu+b5fQHILRUJfycpxErazPYXcSM+V/m/al/Gg079WXwLaQU1n71u59jWa0POw==,iv:A64UL62RbiZP+eYOpppp/PlLN67sH/QBx84rwcy8q0g=,tag:YT7+K1e3pegil/QK5T5GQg==,type:str]
    known_hosts: ENC[AES256_GCM,data:9UV739iFTWX/sGYWoYmo78Cvj5xAdSmdqMuJ4CJ40rhp1Z0tmVfomV41ap9h15/oG6nPutB/HV4q19r7ms/3aOF2a5aq15bE9/vzSeCRDuCaGEliGwYoHK5T7DCmM9H0ku5JjiI3JFEsKrGYBGfDfEjhWH8z6BISz5cHVlOkATU68ZgKOCquRwBuXzO6UjAoLxHdJrH3g7aDXgSD9vAKin7mKHEq1ByR4OO5,iv:y0q6jm0V73hGhrwgbP+fpI1BKY8rHucE7usWxc0iEBU=,tag:IPsZtoFxzwqKiYRV8YlfGg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4anhUbHg4V01nYjFrdjRw
            NS9MYjJMbEpmR0JrOElzdTBWK2F5a2JjaUFBCnFKWExoejEzMTJDSWw3ZXVUSVNI
            ZHdCdm5kVkNnb1R0RloyUC9hTWhhbGsKLS0tIDFxd0VvOWdXVm1SY010OHl0S1Jx
            KzFCSmNrQ3BSWnJxK3hWS3FhQlNyYlUKxl2kqW91MbLTfw3I+E8UzMvA+vEH5kyO
            Czu46EzMvnN0kLyvmq09Nkp5pV3og2g+cwJ52AlFfqpkIzpvQ1EtTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T13:43:57Z"
    mac: ENC[AES256_GCM,data:rlIY5E4bqJXDSXF4tEW3o1QONb2Fu0Z4a3tL4AmoENVqjGZWfb0T2E5hjGpIy1E7H5G2kYB4++y/ZEfn8U7sSh30cRqfDoLUEU5l5eq6v2tvI4eCGHlrP1jfTX9wwnJxvg/22jrpx4fn+SnJewBTHQp4THHIGbh9XsEZEsjw+18=,iv:YpNo8F2nL84z1V6vfABHYVqCwcoZi5np1nZ2cUEdqnw=,tag:/cfzbPvMyN0A5XfmKO6XKQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
