apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automatic-ripping-machine
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/automatic-ripping-machine/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
